main: me.zombie_striker.fishingoverhaul.FishingOverhaul
name: FishingOverhaul
version: '1.0'
description: A fishing plugin
author: Zombie_Striker
api-version: 1.18
commands:
  fish:
    description: The main fish command
    aliases:
      - fo
    permission: fishingoverhaul.appraise
    permission-message: You do not have permission!
    usage: /fishingoverhaul
permissions:
  fishingoverhaul.appraise:
    description: Permission to appraise fish.
    default: op
  fishingoverhaul.*:
    description: The master permission
    default: op
    children:
      fishingoverhaul.appraise: true